### PR TITLE
Get dependabot pr working

### PR DESCRIPTION
**Pull request by ctubbsii**
* Includes fix from #9 and fixes build
  * Add missing .hasAttr() interface method to test class
* Unsuppress fixable deprecation warnings and fix all warnings
  * Use CorsConfigBuilder instead of CorsConfig.Builder
  * Use HttpHeaderNames instead of HttpHeaders.Names
  * Use .x() instead of .getX() methods of HttpRequest
  * Use .isClient() instead of comparing with JdkSslClientContext.class
  * Use new EmbeddedChannel() instead of null for test

The most notable changes are the use of the lowercase versions of HTTP
header field names (HttpHeaderNames instead of HttpHeaders.Names),
because these are case-insensitive, but HTTP/2 converts them to
lowercase as part of the protocol. Any code that looks at headers and
doesn't treat them in a case-insensitive way (like putting them in maps
without using the normalized lowercase form) was already wrong in
HTTP/1.x and prone to bugs (and probably will result in an error with
HTTP/2) and should be fixed in subsequent PRs. These become more obvious
when the code uses the mixed-case versions in HttpHeaders.Name instead
of the all-lowercase names in HttpHeaderNames and tests break, but they
can also break in production if the HTTP client sends them in an
unexpected case for HTTP/1.x and qonduit code doesn't handle it
properly.

### CODE REVIEW

**Comment by dlmarion** [comment]
+1 Looks good.

**Comment by ctubbsii** [comment]
I spent some time looking at how qonduit uses headers and I can't see any places where it's incorrectly being case-sensitive about header names. The riskiest places seem to all be going through library APIs (either Java's or Netty's), where it would be their responsibility to do the case-insensitive comparison. So, I think Qonduit is okay in this regard. If I missed something, hopefully it will manifest itself prominently, so the fix will be obvious later.

**Comment by dlmarion** [comment]
I think I found one at https://github.com/NationalSecurityAgency/qonduit/blob/master/client/src/main/java/qonduit/client/websocket/WebSocketClient.java#L121

**Comment by ctubbsii** [comment]
Cookie naming is different from the name of the HTTP header fields themselves (such as a "set-cookie" or "cookie" or "content-type" header fields).

For cookie names, I found https://stackoverflow.com/questions/11311893/is-the-name-of-a-cookie-case-sensitive ; I think it would be weird for a client to receive a QSESSIONID cookie and respond in a subsequent request with a modified case, so it's probably fine to treat it like it's case-sensitive.

**Pull request merged**
